# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubbishbin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wastename_text', models.CharField(max_length=200)),
                ('wcount', models.IntegerField(default=0)),
                ('rubbishbin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='we.Rubbishbin')),
            ],
        ),
    ]
