# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we', '0003_question_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.AddField(
            model_name='question',
            name='first_desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='fourth_desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='img_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('B', 'Multi choice'), ('C', 'Image based'), ('A', 'Single choice'), ('D', 'Video based')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='question',
            name='second_desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='third_desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='video_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_order',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice',
            field=models.CharField(choices=[('A', 'A is the correct answer'), ('B', 'B is the correct answer'), ('C', 'C is the correct answer'), ('D', 'D is the correct answer')], default='A', max_length=1),
        ),
    ]
