# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we', '0005_question_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_desc',
            field=models.CharField(default='', max_length=300),
        ),
    ]
