# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we', '0007_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(default='', max_length=200)),
                ('question_desc', models.CharField(default='', max_length=300)),
                ('question_choice', models.CharField(choices=[('TRUE', 'Description is true'), ('FALSE', 'Description is false')], default='TRUE', max_length=5)),
                ('question_score', models.IntegerField(default=0)),
                ('question_total_times', models.IntegerField(default=0)),
            ],
        ),
    ]
