# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we', '0008_truefalsequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeepInMindQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(default='', max_length=200)),
                ('question_content', models.CharField(default='', max_length=500)),
                ('question_score', models.IntegerField(default=0)),
                ('question_total_times', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WhichBinQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(default='', max_length=200)),
                ('question_image', models.CharField(default='', max_length=200)),
                ('question_score', models.IntegerField(default=0)),
                ('question_total_times', models.IntegerField(default=0)),
            ],
        ),
    ]
