# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we', '0009_keepinmindquestion_whichbinquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='keepinmindquestion',
            name='question_choice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whichbinquestion',
            name='question_choice',
            field=models.CharField(choices=[('YELLOW', 'Should be put into yellow waste bin'), ('RED', 'Should be put into red waste bin'), ('GREEN', 'Should be put into green waste bin')], default='RED', max_length=5),
        ),
    ]
