# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we', '0010_auto_20160122_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whichbinquestion',
            name='question_choice',
            field=models.CharField(choices=[('YELLOW', 'Should be put into yellow waste bin'), ('RED', 'Should be put into red waste bin'), ('GREEN', 'Should be put into green waste bin')], default='RED', max_length=10),
        ),
    ]
