# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we', '0011_auto_20160122_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='whichbinquestion',
            name='question_waste_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
