# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we', '0012_whichbinquestion_question_waste_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keepinmindquestion',
            name='question_choice',
        ),
        migrations.AddField(
            model_name='keepinmindquestion',
            name='question_choice_alpha',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='keepinmindquestion',
            name='question_choice_beta',
            field=models.CharField(default='', max_length=20),
        ),
    ]
