# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we', '0016_truefalsequestion_question_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='fourth_desc',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='img_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='video_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
